"""
Trading Bot Framework (AutoBot variants)

Framework for creating complete, self-contained automated trading bots for the system.

Each trading bot is a complete decision engine with:
- Custom indicator suites and technical analysis
- Automated entry/exit rules and logic
- Integrated risk management and position sizing
- Performance tracking and diagnostics
- Alert/webhook capabilities for automation
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, List, Optional, Any, Callable, Protocol
import uuid

import pandas as pd
import numpy as np

from pearlalgo.utils.logger import logger
from .market_regime_detector import MarketRegime, MarketRegimeDetector, market_regime_detector
from .ml_signal_filter import MLSignalFilter, ml_signal_filter


class IndicatorSuite(Protocol):
    """Protocol for indicator suites (like Lux Algo's PAC/S&O/OSC)."""

    def calculate_signals(self, df: pd.DataFrame) -> Dict[str, Any]:
        """Calculate indicator signals for the bot."""
        ...

    def get_features(self, df: pd.DataFrame) -> Dict[str, float]:
        """Extract numeric features for decision making."""
        ...


@dataclass
class BotConfig:
    """Configuration for an automated trading bot."""

    # Basic identification
    name: str
    description: str
    version: str = "1.0.0"

    # Trading parameters
    symbol: str = "MNQ"
    timeframe: str = "5m"
    max_positions: int = 1

    # Risk management
    risk_per_trade: float = 0.01  # 1% of capital
    stop_loss_pct: float = 0.005   # 0.5% stop loss
    take_profit_pct: float = 0.01  # 1% take profit
    max_drawdown_pct: float = 0.05 # 5% max drawdown

    # Entry filters
    min_confidence: float = 0.6
    min_volume: int = 100
    market_hours_only: bool = True

    # Market regime settings
    enable_regime_filtering: bool = True
    allowed_regimes: List[str] = field(default_factory=lambda: ["trending_bull", "trending_bear", "ranging"])
    regime_risk_multiplier: float = 1.0

    # ML enhancement settings
    enable_ml_enhancement: bool = True

    # Bot-specific parameters (to be extended by subclasses)
    parameters: Dict[str, Any] = field(default_factory=dict)

    # Alert/webhook settings
    enable_alerts: bool = True
    webhook_url: Optional[str] = None
    alert_filters: List[str] = field(default_factory=list)


@dataclass
class TradeSignal:
    """Trading signal generated by a bot."""

    # Required fields (no defaults) - must come first
    direction: str  # "long", "short"
    confidence: float  # 0.0 to 1.0
    entry_price: float
    stop_loss: float
    take_profit: float
    bot_name: str
    bot_version: str
    reason: str

    # Fields with defaults
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    indicators_used: List[str] = field(default_factory=list)
    features: Dict[str, float] = field(default_factory=dict)
    risk_reward_ratio: float = 0.0
    position_size_pct: float = 0.01
    status: str = "generated"  # generated, executed, closed
    execution_price: Optional[float] = None
    exit_price: Optional[float] = None
    pnl: Optional[float] = None

    # Market regime information
    market_regime: Optional[str] = None
    regime_confidence: float = 0.0
    regime_adjusted_confidence: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "signal_id": self.signal_id,
            "timestamp": self.timestamp.isoformat(),
            "direction": self.direction,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "bot_name": self.bot_name,
            "bot_version": self.bot_version,
            "reason": self.reason,
            "indicators_used": self.indicators_used,
            "features": self.features,
            "risk_reward_ratio": self.risk_reward_ratio,
            "position_size_pct": self.position_size_pct,
            "status": self.status,
            "execution_price": self.execution_price,
            "exit_price": self.exit_price,
            "pnl": self.pnl,
        }


@dataclass
class BotPerformance:
    """Performance metrics for a trading bot."""

    bot_name: str
    total_signals: int = 0
    executed_signals: int = 0
    winning_trades: int = 0
    losing_trades: int = 0

    total_pnl: float = 0.0
    gross_profit: float = 0.0
    gross_loss: float = 0.0
    largest_win: float = 0.0
    largest_loss: float = 0.0

    win_rate: float = 0.0
    profit_factor: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    avg_risk_reward: float = 0.0

    max_drawdown: float = 0.0
    current_drawdown: float = 0.0

    sharpe_ratio: float = 0.0
    sortino_ratio: float = 0.0

    # Time-based metrics
    total_trading_days: int = 0
    avg_trades_per_day: float = 0.0

    # Internal tracking for drawdown and ratios
    _equity_curve: List[float] = field(default_factory=list)
    _peak_equity: float = 0.0
    _returns: List[float] = field(default_factory=list)

    def update_from_signal(self, signal: TradeSignal) -> None:
        """Update performance metrics from a closed signal."""
        if signal.status != "closed" or signal.pnl is None:
            return

        self.total_signals += 1
        if signal.execution_price is not None:
            self.executed_signals += 1

        pnl = signal.pnl
        self.total_pnl += pnl

        # Track equity curve for drawdown calculation
        self._equity_curve.append(self.total_pnl)
        self._peak_equity = max(self._peak_equity, self.total_pnl)
        
        # Track returns for Sharpe/Sortino calculation
        if len(self._equity_curve) > 1:
            return_pct = (pnl / abs(self._equity_curve[-2])) if self._equity_curve[-2] != 0 else 0.0
            self._returns.append(return_pct)

        if pnl > 0:
            self.winning_trades += 1
            self.gross_profit += pnl
            self.largest_win = max(self.largest_win, pnl)
        else:
            self.losing_trades += 1
            self.gross_loss += abs(pnl)
            self.largest_loss = max(self.largest_loss, abs(pnl))

        # Recalculate derived metrics
        self._recalculate_metrics()

    def _recalculate_metrics(self) -> None:
        """Recalculate derived performance metrics."""
        total_trades = self.winning_trades + self.losing_trades

        if total_trades > 0:
            self.win_rate = self.winning_trades / total_trades

        if self.gross_loss > 0:
            self.profit_factor = self.gross_profit / self.gross_loss

        if self.winning_trades > 0:
            self.avg_win = self.gross_profit / self.winning_trades

        if self.losing_trades > 0:
            self.avg_loss = self.gross_loss / self.losing_trades

        # Risk-reward ratio
        if self.avg_loss > 0:
            self.avg_risk_reward = self.avg_win / self.avg_loss

        # Calculate drawdown
        if self._equity_curve:
            current_equity = self._equity_curve[-1]
            self.current_drawdown = self._peak_equity - current_equity
            self.max_drawdown = max(self.max_drawdown, self.current_drawdown)

        # Calculate Sharpe and Sortino ratios
        if len(self._returns) > 1:
            returns_array = np.array(self._returns)
            mean_return = np.mean(returns_array)
            std_return = np.std(returns_array)
            
            # Sharpe ratio (annualized, assuming daily returns)
            if std_return > 0:
                self.sharpe_ratio = (mean_return / std_return) * np.sqrt(252)
            
            # Sortino ratio (only downside deviation)
            downside_returns = returns_array[returns_array < 0]
            if len(downside_returns) > 0:
                downside_std = np.std(downside_returns)
                if downside_std > 0:
                    self.sortino_ratio = (mean_return / downside_std) * np.sqrt(252)


class TradingBot(ABC):
    """
    Abstract base class for trading bots (AutoBot variants).

    Each bot is a complete, self-contained trading system for the platform,
    combining custom indicators, automated rules, risk management, and performance tracking.
    """

    def __init__(self, config: BotConfig):
        self.config = config
        self.performance = BotPerformance(bot_name=config.name)
        self.active_signals: List[TradeSignal] = []
        self.signal_history: List[TradeSignal] = []

        # Bot state
        self.is_active = True
        self.last_analysis_time: Optional[datetime] = None

        logger.info(f"Initialized {config.name} v{config.version}: {config.description}")

    @property
    @abstractmethod
    def name(self) -> str:
        """Bot name/identifier."""
        pass

    @property
    @abstractmethod
    def description(self) -> str:
        """Human-readable description of the bot's strategy."""
        pass

    @property
    @abstractmethod
    def strategy_type(self) -> str:
        """Strategy type (trend, breakout, reversal, etc.)."""
        pass

    @abstractmethod
    def get_indicator_suite(self) -> IndicatorSuite:
        """Return the bot's indicator suite (PAC/S&O/OSC equivalent)."""
        pass

    @abstractmethod
    def generate_signal_logic(self, df: pd.DataFrame, indicators: Dict[str, Any]) -> Optional[TradeSignal]:
        """
        Core signal generation logic.

        This is where each bot implements its unique trading rules,
        similar to how Lux Algo's AI generates specific entry/exit rules.
        """
        pass

    def analyze(self, market_data: Dict) -> List[TradeSignal]:
        """
        Main analysis method with market regime awareness.

        Similar to Lux Algo's strategy analysis pipeline but with regime filtering.
        """
        if not self.is_active:
            return []

        try:
            df = market_data.get('df')
            if df is None or df.empty:
                return []

            # Apply market filters
            if not self._passes_market_filters(df):
                return []

            # Detect market regime if enabled
            regime_info = None
            if self.config.enable_regime_filtering:
                regime_info = self._detect_market_regime(df)

                # Skip trading if current regime not allowed
                if regime_info and regime_info[0].value not in self.config.allowed_regimes:
                    logger.debug(f"{self.name}: Skipping signal in {regime_info[0].value} regime")
                    return []

            # Get latest bar data
            latest_bar = market_data.get('latest_bar', {})

            # Calculate indicators
            indicator_suite = self.get_indicator_suite()
            indicators = indicator_suite.calculate_signals(df)

            # Generate signal using bot-specific logic
            signal = self.generate_signal_logic(df, indicators)

            if signal:
                # Apply ML enhancement if enabled
                if self.config.enable_ml_enhancement:
                    signal = ml_signal_filter.enhance_signal(signal, df)

                # Apply regime-aware risk management
                signal = self._apply_risk_management(signal, df, regime_info)

                # Validate signal with regime adjustments
                if self._validate_signal(signal, regime_info):
                    # Add regime information to signal
                    if regime_info:
                        signal.market_regime = regime_info[0].value
                        signal.regime_confidence = regime_info[2]
                        # Apply regime confidence adjustment
                        regime_filters = market_regime_detector.get_regime_filter(regime_info[0])
                        confidence_boost = regime_filters.get('confidence_boost', 0.0)
                        signal.regime_adjusted_confidence = min(1.0, signal.confidence + confidence_boost)

                    # Track active signals
                    self.active_signals.append(signal)
                    self.signal_history.append(signal)

                    # Send alerts if enabled
                    if self.config.enable_alerts:
                        self._send_alert(signal)

                    self.last_analysis_time = datetime.now(timezone.utc)

                    return [signal]

            return []

        except Exception as e:
            logger.error(f"Error in {self.name} analysis: {e}", exc_info=True)
            return []

    def update_signal_status(self, signal_id: str, status: str,
                           execution_price: Optional[float] = None,
                           exit_price: Optional[float] = None) -> None:
        """Update the status of an active signal."""
        for signal in self.active_signals:
            if signal.signal_id == signal_id:
                signal.status = status
                signal.execution_price = execution_price
                signal.exit_price = exit_price

                if exit_price and execution_price:
                    if signal.direction == "long":
                        signal.pnl = (exit_price - execution_price) / execution_price
                    else:  # short
                        signal.pnl = (execution_price - exit_price) / execution_price

                    # Update performance metrics
                    self.performance.update_from_signal(signal)

                    # Update ML model with trade result if enabled
                    if self.config.enable_ml_enhancement and signal.pnl is not None:
                        ml_signal_filter.update_from_trade_result(
                            signal, signal.pnl, execution_price is not None
                        )

                # Remove from active signals
                self.active_signals.remove(signal)
                break

    def get_performance_report(self) -> Dict[str, Any]:
        """Get comprehensive performance report like Lux Algo's strategy metrics."""
        return {
            "bot_name": self.name,
            "strategy_type": self.strategy_type,
            "description": self.description,
            "config": self.config.__dict__,
            "performance": self.performance.__dict__,
            "active_signals": len(self.active_signals),
            "total_signals_history": len(self.signal_history),
            "last_analysis": self.last_analysis_time.isoformat() if self.last_analysis_time else None,
            "is_active": self.is_active,
        }

    def _passes_market_filters(self, df: pd.DataFrame) -> bool:
        """Apply basic market filters before signal generation."""
        if not self.config.market_hours_only:
            return True

        # Check if we're in market hours (simplified - could be enhanced)
        # This would integrate with the existing market hours logic
        return True  # Placeholder

    def _detect_market_regime(self, df: pd.DataFrame) -> Optional[tuple[MarketRegime, Any, float]]:
        """Detect current market regime for regime-aware trading."""
        try:
            return market_regime_detector.detect_regime(df)
        except Exception as e:
            logger.warning(f"Failed to detect market regime: {e}")
            return None

    def _apply_risk_management(self, signal: TradeSignal, df: pd.DataFrame,
                              regime_info: Optional[tuple] = None) -> TradeSignal:
        """Apply regime-aware risk management rules to the signal."""
        # Base risk amount
        risk_amount = self.config.risk_per_trade

        # Apply regime-based risk adjustment
        if regime_info:
            regime, metrics, confidence = regime_info
            regime_filters = market_regime_detector.get_regime_filter(regime)
            risk_multiplier = regime_filters.get('risk_multiplier', 1.0)
            risk_amount *= risk_multiplier * self.config.regime_risk_multiplier

        # Calculate position size based on risk per trade
        stop_distance = abs(signal.entry_price - signal.stop_loss)

        if stop_distance > 0:
            position_size_pct = min(risk_amount / stop_distance, 0.1)  # Max 10%
            signal.position_size_pct = position_size_pct

        # Calculate risk-reward ratio
        tp_distance = abs(signal.take_profit - signal.entry_price)
        if stop_distance > 0:
            signal.risk_reward_ratio = tp_distance / stop_distance

        return signal

    def _validate_signal(self, signal: TradeSignal, regime_info: Optional[tuple] = None) -> bool:
        """Validate signal against bot configuration with regime awareness."""
        # Use regime-adjusted confidence if available
        effective_confidence = signal.regime_adjusted_confidence if signal.regime_adjusted_confidence > 0 else signal.confidence

        # Check confidence threshold
        if effective_confidence < self.config.min_confidence:
            return False

        # Check risk-reward ratio (minimum 1:1)
        if signal.risk_reward_ratio < 1.0:
            return False

        # Check position limits (may be regime-adjusted)
        max_positions = self.config.max_positions
        if regime_info:
            regime, metrics, confidence = regime_info
            regime_filters = market_regime_detector.get_regime_filter(regime)
            max_positions = min(max_positions, regime_filters.get('max_positions', max_positions))

        if len(self.active_signals) >= max_positions:
            return False

        # Check drawdown limits
        if self.performance.current_drawdown >= self.config.max_drawdown_pct:
            return False

        return True

    def _send_alert(self, signal: TradeSignal) -> None:
        """Send alerts via webhooks or other channels."""
        if not self.config.webhook_url:
            return

        try:
            alert_data = {
                "bot_name": signal.bot_name,
                "signal_id": signal.signal_id,
                "direction": signal.direction,
                "confidence": signal.confidence,
                "entry_price": signal.entry_price,
                "stop_loss": signal.stop_loss,
                "take_profit": signal.take_profit,
                "reason": signal.reason,
                "timestamp": signal.timestamp.isoformat(),
            }

            # Here you would implement webhook sending
            # For now, just log it
            logger.info(f"ALERT: {self.name} generated {signal.direction} signal at {signal.entry_price}")

        except Exception as e:
            logger.error(f"Failed to send alert for {signal.signal_id}: {e}")

    def reset_performance(self) -> None:
        """Reset performance metrics (useful for backtesting)."""
        self.performance = BotPerformance(bot_name=self.config.name)
        self.active_signals = []
        self.signal_history = []


# Factory function to create bots by name
BOT_REGISTRY: Dict[str, type[TradingBot]] = {}


def register_bot(bot_class: type[TradingBot]) -> None:
    """Register a bot class for creation by name."""
    BOT_REGISTRY[bot_class.__name__] = bot_class


def create_bot(bot_name: str, config: BotConfig) -> TradingBot:
    """Create a bot instance by name."""
    if bot_name not in BOT_REGISTRY:
        raise ValueError(f"Bot '{bot_name}' not registered")

    return BOT_REGISTRY[bot_name](config)