"""
Visual regression tests for dashboard trade overlay rendering.

This suite locks in the Telegram-style trade overlay behavior used in production:
- Smart marker overlay configuration (entry/exit/path semantics)
- Max-N pruning (`trade_markers_max`)
- Overlay legend presence/wording

To update baselines after intentional visual changes:
  .venv/bin/python scripts/testing/regenerate_trade_overlay_baselines.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pytest

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "src"))

from tests.fixtures.deterministic_data import (  # noqa: E402
    FIXED_TITLE_TIME,
    SEED,
    generate_deterministic_ohlcv,
)
from tests.fixtures.trade_overlay_fixtures import (  # noqa: E402
    apply_telegram_render_profile,
    build_trade_list,
    deterministic_regime_info,
)
from tests.fixtures.visual_regression_utils import (  # noqa: E402
    DEFAULT_MAX_DIFF_PIXELS_PCT,
    DEFAULT_PIXEL_TOLERANCE,
    DETERMINISM_MAX_DIFF_PIXELS_PCT,
    DETERMINISM_PIXEL_TOLERANCE,
    compare_images,
    format_regression_failure_message,
    load_image_as_array,
    save_diff_artifact,
    validate_png_file,
)


FIXTURES_DIR = project_root / "tests" / "fixtures" / "charts"
DIFF_OUTPUT_DIR = project_root / "tests" / "artifacts"

# Baseline images generated by:
#   scripts/testing/regenerate_trade_overlay_baselines.py
BASELINES = {
    "normal_pairs_max20": FIXTURES_DIR / "trade_overlay_normal_pairs_max20.png",
    "dense_pairs_max20": FIXTURES_DIR / "trade_overlay_dense_pairs_max20.png",
    "dense_pairs_clean3": FIXTURES_DIR / "trade_overlay_dense_pairs_clean3.png",
}

PIXEL_TOLERANCE = DEFAULT_PIXEL_TOLERANCE
MAX_DIFF_PIXELS_PCT = DEFAULT_MAX_DIFF_PIXELS_PCT


def _make_generator():
    try:
        from pearlalgo.market_agent.chart_generator import ChartConfig, ChartGenerator
    except ImportError as e:
        pytest.skip(f"Chart generator not available: {e}")

    cfg = ChartConfig()
    apply_telegram_render_profile(cfg)

    # Trade overlay baseline: "pairs" (entry+exit+connector), no letters.
    cfg.smart_marker_show_letters = False
    cfg.smart_marker_show_entry = True
    cfg.smart_marker_show_exit = True
    cfg.smart_marker_show_path = True
    cfg.smart_marker_path_arrowheads = False
    cfg.smart_marker_path_fade_by_age = False
    cfg.smart_marker_path_label_last_pnl = False

    return ChartGenerator(cfg)


def _render_trade_overlay_chart(*, dense: bool, trade_markers_max: int) -> Path:
    data = generate_deterministic_ohlcv(num_bars=220, base_price=26300.0)
    lookback = 8 * 60 // 5  # 8h of 5m bars

    trades = build_trade_list(
        data,
        lookback_bars=lookback,
        num_trades=20 if dense else 5,
        spacing_bars=2 if dense else 18,
        hold_bars=10 if dense else 8,
        start_offset_into_window=10 if dense else 8,
    )

    generator = _make_generator()
    path = generator.generate_dashboard_chart(
        data=data,
        symbol="MNQ",
        timeframe="5m",
        lookback_bars=lookback,
        range_label="8h",
        figsize=(8, 12),
        dpi=200,
        render_mode="telegram",
        show_sessions=True,
        show_key_levels=True,
        show_vwap=True,
        show_ma=True,
        ma_periods=[20, 50, 200],
        show_rsi=True,
        show_pressure=True,
        title_time=FIXED_TITLE_TIME,
        trades=trades,
        regime_info=deterministic_regime_info(confidence=0.64),
        # Telegram-only render tuning (stable, tested)
        show_ema_crossover_markers=False,
        show_trade_overlay_legend=True,
        trade_markers_max=int(trade_markers_max),
        save_pad_inches=0.12,
        telegram_top_headroom_pct=0.045,
        optimize_png=False,
    )

    assert path is not None, "Chart generation returned None"
    out = Path(path)
    assert out.exists(), f"Chart file not created: {out}"
    assert out.stat().st_size > 0, "Chart file is empty"
    return out


class TestTradeOverlayBaselineValidity:
    """Baseline artifact health checks for trade overlay charts."""

    @pytest.mark.parametrize("name", sorted(BASELINES.keys()))
    def test_baseline_exists(self, name: str):
        p = BASELINES[name]
        assert p.exists(), (
            f"Trade overlay baseline not found: {p}\n"
            "Update baselines:\n"
            "  .venv/bin/python scripts/testing/regenerate_trade_overlay_baselines.py"
        )

    @pytest.mark.parametrize("name", sorted(BASELINES.keys()))
    def test_baseline_is_valid_png(self, name: str):
        p = BASELINES[name]
        if not p.exists():
            pytest.skip("Baseline missing")
        valid, error = validate_png_file(p)
        assert valid, f"Baseline is invalid: {error}"


class TestTradeOverlayVisualRegression:
    """Image-diff regression tests for trade overlays."""

    @pytest.mark.parametrize(
        "baseline_key,dense,trade_markers_max",
        [
            ("normal_pairs_max20", False, 20),
            ("dense_pairs_max20", True, 20),
            ("dense_pairs_clean3", True, 3),
        ],
    )
    def test_trade_overlay_visual_regression(self, baseline_key: str, dense: bool, trade_markers_max: int):
        baseline_path = BASELINES[baseline_key]
        if not baseline_path.exists():
            pytest.skip("Baseline missing (run baseline regeneration script)")

        chart_path = _render_trade_overlay_chart(dense=dense, trade_markers_max=trade_markers_max)
        try:
            actual = load_image_as_array(chart_path)
            expected = load_image_as_array(baseline_path)

            assert actual is not None, f"Could not load actual chart: {chart_path}"
            assert expected is not None, f"Could not load baseline: {baseline_path}"

            passed, mean_diff, diff_pct, diff_image = compare_images(
                actual,
                expected,
                tolerance=PIXEL_TOLERANCE,
                max_diff_pct=MAX_DIFF_PIXELS_PCT,
            )

            if not passed:
                artifact_dir = save_diff_artifact(
                    actual,
                    expected,
                    diff_image,
                    f"trade_overlay_{baseline_key}",
                    output_dir=DIFF_OUTPUT_DIR,
                )
                pytest.fail(
                    format_regression_failure_message(
                        mean_diff=mean_diff,
                        diff_pct=diff_pct,
                        tolerance=PIXEL_TOLERANCE,
                        max_diff_pct=MAX_DIFF_PIXELS_PCT,
                        artifact_dir=artifact_dir,
                        baseline_update_command=(
                            ".venv/bin/python scripts/testing/regenerate_trade_overlay_baselines.py"
                        ),
                    )
                )
        finally:
            chart_path.unlink(missing_ok=True)

    def test_trade_overlay_determinism(self):
        """Same inputs should produce near-identical outputs (within tight tolerance)."""

        np.random.seed(SEED)
        path1 = _render_trade_overlay_chart(dense=False, trade_markers_max=20)

        np.random.seed(SEED)
        path2 = _render_trade_overlay_chart(dense=False, trade_markers_max=20)

        try:
            img1 = load_image_as_array(path1)
            img2 = load_image_as_array(path2)

            assert img1 is not None and img2 is not None

            passed, mean_diff, diff_pct, _ = compare_images(
                img1,
                img2,
                tolerance=DETERMINISM_PIXEL_TOLERANCE,
                max_diff_pct=DETERMINISM_MAX_DIFF_PIXELS_PCT,
            )

            assert passed, (
                f"Trade overlay determinism violation\n"
                f"  Mean diff: {mean_diff:.4f}, Diff pct: {diff_pct:.4f}%"
            )
        finally:
            path1.unlink(missing_ok=True)
            path2.unlink(missing_ok=True)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])

