"""
LLM Signal Annotator

Provides AI-powered annotations for trading signals, including:
- Explanation of why the signal appeared
- Key supporting factors
- Potential risks
- Overall confidence assessment

The LLM acts as a "Signal Analyst" - it READS context and ANNOTATES signals,
but NEVER makes trading decisions. All annotations are purely informational.

This module is designed to be:
- Non-blocking (async, with timeout)
- Gracefully degrading (failures don't affect signal processing)
- Cost-efficient (concise prompts, optional batching)
"""

from __future__ import annotations

import asyncio
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pearlalgo.utils.logger import logger

# Import Claude client (optional dependency)
try:
    from pearlalgo.utils.claude_client import (
        ClaudeClient,
        ClaudeAPIError,
        get_claude_client,
        OPENAI_AVAILABLE,
    )
except ImportError:
    ClaudeClient = None
    ClaudeAPIError = Exception
    get_claude_client = lambda: None
    OPENAI_AVAILABLE = False

# Backward compatibility
ANTHROPIC_AVAILABLE = OPENAI_AVAILABLE


# ============================================================================
# Prompt Templates
# ============================================================================

SIGNAL_ANNOTATION_SYSTEM_PROMPT = """You are a trading signal analyst for an NQ/MNQ futures intraday trading system.

Your role is to ANALYZE signals generated by a technical trading system and provide:
1. A brief explanation of why this signal appeared
2. Key supporting factors (2-3 bullet points)
3. Potential risks (1-2 bullet points)
4. Overall assessment (High/Medium/Low confidence based on confluence)

RULES:
- Be concise and actionable (this will be displayed on Telegram)
- Focus on technical confluence, not predictions
- Never give trading advice or recommendations
- Use trading terminology appropriate for futures traders
- Keep explanations under 100 words total

Output ONLY valid JSON with these fields:
{
  "explanation": "2-3 sentence analysis",
  "key_factors": ["factor1", "factor2"],
  "risks": ["risk1"],
  "confidence_note": "High confidence" | "Medium confidence" | "Low confidence",
  "summary_emoji": "🟢" | "🟡" | "🔴"
}"""

SIGNAL_ANNOTATION_USER_TEMPLATE = """Analyze this trading signal:

Signal Type: {signal_type}
Direction: {direction}
Confidence: {confidence:.1%}
Entry: ${entry_price:.2f}
Stop Loss: ${stop_loss:.2f}
Take Profit: ${take_profit:.2f}
Risk/Reward: {risk_reward:.2f}

Market Context:
- Regime: {regime_type} ({volatility} volatility)
- Session: {session}
- RSI: {rsi:.1f}
- MACD Histogram: {macd_hist:+.3f}
- Volume Ratio: {volume_ratio:.2f}x average
- ATR: {atr:.2f} ({atr_pct:.3%} of price)

Custom Indicators:
{custom_indicators}

Recent Performance: {recent_wr}% win rate ({recent_trades} trades)

Provide your analysis as JSON."""


# ============================================================================
# Data Classes
# ============================================================================

@dataclass
class SignalAnnotation:
    """Annotation result from LLM analysis."""
    explanation: str = ""
    key_factors: List[str] = field(default_factory=list)
    risks: List[str] = field(default_factory=list)
    confidence_note: str = "Medium confidence"
    summary_emoji: str = "🟡"
    
    # Metadata
    model: str = ""
    latency_ms: int = 0
    error: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "explanation": self.explanation,
            "key_factors": self.key_factors,
            "risks": self.risks,
            "confidence_note": self.confidence_note,
            "summary_emoji": self.summary_emoji,
            "model": self.model,
            "latency_ms": self.latency_ms,
            "error": self.error,
        }
    
    def format_telegram(self) -> str:
        """Format annotation for Telegram message."""
        if self.error:
            return ""
        
        lines = []
        
        # Summary
        lines.append(f"{self.summary_emoji} *AI Analysis:* {self.explanation}")
        
        # Key factors
        if self.key_factors:
            lines.append("\n*Key Factors:*")
            for factor in self.key_factors[:3]:
                lines.append(f"  • {factor}")
        
        # Risks
        if self.risks:
            lines.append("\n*Risks:*")
            for risk in self.risks[:2]:
                lines.append(f"  ⚠️ {risk}")
        
        # Confidence
        lines.append(f"\n*Assessment:* {self.confidence_note}")
        
        return "\n".join(lines)
    
    @classmethod
    def from_error(cls, error: str) -> "SignalAnnotation":
        """Create annotation from error."""
        return cls(
            explanation="",
            error=error,
        )


# ============================================================================
# Signal Annotator
# ============================================================================

class LLMSignalAnnotator:
    """
    LLM-powered signal annotator for trading signals.
    
    Uses Claude to analyze signals and provide human-readable explanations.
    All operations are non-blocking and fail gracefully.
    
    Configuration:
    - enabled: Master toggle for annotations
    - model: Claude model to use (default: claude-sonnet-4-20250514)
    - timeout_seconds: Max time to wait for annotation (default: 5s)
    - batch_mode: Whether to batch multiple signals (default: False)
    """
    
    def __init__(
        self,
        enabled: bool = True,
        model: str = "claude-sonnet-4-20250514",
        timeout_seconds: float = 5.0,
        batch_mode: bool = False,
    ):
        """
        Initialize the signal annotator.
        
        Args:
            enabled: Whether annotation is enabled
            model: Claude model to use
            timeout_seconds: Timeout for annotation requests
            batch_mode: Whether to batch signals (not yet implemented)
        """
        self.enabled = enabled
        self.model = model
        self.timeout_seconds = timeout_seconds
        self.batch_mode = batch_mode
        
        # Initialize Claude client (may be None if not configured)
        self._client: Optional[ClaudeClient] = None
        if enabled and OPENAI_AVAILABLE:
            try:
                self._client = get_claude_client()
            except Exception as e:
                logger.warning(f"Failed to initialize Claude client for annotations: {e}")
        
        # Stats
        self._total_requests = 0
        self._successful_requests = 0
        self._total_latency_ms = 0
        
        status = "enabled" if self._client else "disabled (client unavailable)"
        logger.info(f"LLMSignalAnnotator initialized: {status}, model={model}, timeout={timeout_seconds}s")
    
    @property
    def is_available(self) -> bool:
        """Check if annotation is available."""
        return self.enabled and self._client is not None
    
    def annotate_signal(
        self,
        signal: Dict,
        market_context: Optional[Dict] = None,
        performance_metrics: Optional[Dict] = None,
    ) -> SignalAnnotation:
        """
        Annotate a trading signal synchronously.
        
        This is a blocking call - use annotate_signal_async for non-blocking.
        
        Args:
            signal: Signal dictionary from signal generator
            market_context: Optional additional market context
            performance_metrics: Optional recent performance metrics
            
        Returns:
            SignalAnnotation with analysis results
        """
        if not self.is_available:
            return SignalAnnotation.from_error("Annotator not available")
        
        start_time = datetime.now(timezone.utc)
        self._total_requests += 1
        
        try:
            # Build prompt
            user_prompt = self._build_prompt(signal, market_context, performance_metrics)
            
            # Call Claude
            response = self._client.chat(
                messages=[{"role": "user", "content": user_prompt}],
                system_prompt=SIGNAL_ANNOTATION_SYSTEM_PROMPT,
            )
            
            # Parse response
            annotation = self._parse_response(response)
            
            # Calculate latency
            latency_ms = int((datetime.now(timezone.utc) - start_time).total_seconds() * 1000)
            annotation.latency_ms = latency_ms
            annotation.model = self.model
            
            self._successful_requests += 1
            self._total_latency_ms += latency_ms
            
            logger.debug(f"Signal annotation completed in {latency_ms}ms")
            return annotation
            
        except Exception as e:
            logger.warning(f"Signal annotation failed: {e}")
            return SignalAnnotation.from_error(str(e))
    
    async def annotate_signal_async(
        self,
        signal: Dict,
        market_context: Optional[Dict] = None,
        performance_metrics: Optional[Dict] = None,
    ) -> SignalAnnotation:
        """
        Annotate a trading signal asynchronously with timeout.
        
        This is the recommended method for use in the signal pipeline.
        
        Args:
            signal: Signal dictionary from signal generator
            market_context: Optional additional market context
            performance_metrics: Optional recent performance metrics
            
        Returns:
            SignalAnnotation with analysis results (or error annotation on timeout)
        """
        if not self.is_available:
            return SignalAnnotation.from_error("Annotator not available")
        
        try:
            # Run sync annotation in thread pool with timeout
            loop = asyncio.get_event_loop()
            result = await asyncio.wait_for(
                loop.run_in_executor(
                    None,
                    self.annotate_signal,
                    signal,
                    market_context,
                    performance_metrics,
                ),
                timeout=self.timeout_seconds,
            )
            return result
            
        except asyncio.TimeoutError:
            logger.debug(f"Signal annotation timed out after {self.timeout_seconds}s")
            return SignalAnnotation.from_error(f"Timeout ({self.timeout_seconds}s)")
        except Exception as e:
            logger.warning(f"Async annotation failed: {e}")
            return SignalAnnotation.from_error(str(e))
    
    def _build_prompt(
        self,
        signal: Dict,
        market_context: Optional[Dict],
        performance_metrics: Optional[Dict],
    ) -> str:
        """Build the user prompt for signal annotation."""
        # Extract signal data
        signal_type = signal.get("type", "unknown")
        direction = signal.get("direction", "unknown")
        confidence = signal.get("confidence", 0.0)
        entry_price = signal.get("entry_price", 0.0)
        stop_loss = signal.get("stop_loss", 0.0)
        take_profit = signal.get("take_profit", 0.0)
        
        # Calculate risk/reward
        if direction == "long" and entry_price > 0 and stop_loss > 0:
            risk = entry_price - stop_loss
            reward = take_profit - entry_price if take_profit else 0
            risk_reward = reward / risk if risk > 0 else 0
        elif direction == "short" and entry_price > 0 and stop_loss > 0:
            risk = stop_loss - entry_price
            reward = entry_price - take_profit if take_profit else 0
            risk_reward = reward / risk if risk > 0 else 0
        else:
            risk_reward = 0
        
        # Extract regime data
        regime = signal.get("regime", {})
        regime_type = regime.get("regime", "unknown")
        volatility = regime.get("volatility", "normal")
        session = regime.get("session", "unknown")
        
        # Extract indicators
        indicators = signal.get("indicators", {})
        rsi = indicators.get("rsi", 50.0) or 50.0
        macd_hist = indicators.get("macd_histogram", 0.0) or 0.0
        volume_ratio = indicators.get("volume_ratio", 1.0) or 1.0
        atr = indicators.get("atr", 0.0) or 0.0
        atr_pct = atr / entry_price if entry_price > 0 else 0
        
        # Format custom indicators
        custom_features = signal.get("custom_features", {})
        indicator_metadata = signal.get("indicator_metadata", {})
        custom_lines = []
        
        # Add indicator metadata (from custom indicator signals)
        if indicator_metadata:
            for key, value in indicator_metadata.items():
                if isinstance(value, float):
                    custom_lines.append(f"  - {key}: {value:.3f}")
                else:
                    custom_lines.append(f"  - {key}: {value}")
        
        # Add key custom features (limit to most relevant)
        if custom_features:
            # Prioritize zone-related features
            priority_keys = [
                "sd_in_demand_zone", "sd_in_supply_zone", "sd_zone_strength",
                "pc_trend_bullish", "pc_trend_bearish", "pc_channel_position",
                "smd_bullish_divergence", "smd_bearish_divergence",
            ]
            for key in priority_keys:
                if key in custom_features:
                    value = custom_features[key]
                    if isinstance(value, float) and value > 0:
                        custom_lines.append(f"  - {key}: {value:.2f}")
        
        custom_indicators = "\n".join(custom_lines) if custom_lines else "  (none)"
        
        # Extract performance metrics
        if performance_metrics:
            recent_wr = performance_metrics.get("win_rate", 0.5) * 100
            recent_trades = performance_metrics.get("total_trades", 0)
        else:
            recent_wr = 50.0
            recent_trades = 0
        
        # Build prompt
        return SIGNAL_ANNOTATION_USER_TEMPLATE.format(
            signal_type=signal_type,
            direction=direction,
            confidence=confidence,
            entry_price=entry_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            risk_reward=risk_reward,
            regime_type=regime_type,
            volatility=volatility,
            session=session,
            rsi=rsi,
            macd_hist=macd_hist,
            volume_ratio=volume_ratio,
            atr=atr,
            atr_pct=atr_pct,
            custom_indicators=custom_indicators,
            recent_wr=recent_wr,
            recent_trades=recent_trades,
        )
    
    def _parse_response(self, response: str) -> SignalAnnotation:
        """Parse Claude's JSON response into SignalAnnotation."""
        try:
            # Try to extract JSON from response
            response = response.strip()
            
            # Handle markdown code blocks
            if response.startswith("```"):
                lines = response.split("\n")
                response = "\n".join(lines[1:-1] if lines[-1].startswith("```") else lines[1:])
            
            # Parse JSON
            data = json.loads(response)
            
            return SignalAnnotation(
                explanation=str(data.get("explanation", "")),
                key_factors=data.get("key_factors", [])[:3],
                risks=data.get("risks", [])[:2],
                confidence_note=str(data.get("confidence_note", "Medium confidence")),
                summary_emoji=str(data.get("summary_emoji", "🟡")),
            )
            
        except json.JSONDecodeError as e:
            logger.warning(f"Failed to parse annotation response: {e}")
            # Try to extract useful info from non-JSON response
            if response:
                return SignalAnnotation(
                    explanation=response[:200] if len(response) > 200 else response,
                    confidence_note="Analysis available",
                    summary_emoji="🟡",
                )
            return SignalAnnotation.from_error("Invalid response format")
    
    def get_stats(self) -> Dict[str, Any]:
        """Get annotation statistics."""
        avg_latency = (
            self._total_latency_ms / self._successful_requests
            if self._successful_requests > 0
            else 0
        )
        success_rate = (
            self._successful_requests / self._total_requests
            if self._total_requests > 0
            else 0
        )
        
        return {
            "total_requests": self._total_requests,
            "successful_requests": self._successful_requests,
            "success_rate": success_rate,
            "avg_latency_ms": avg_latency,
            "is_available": self.is_available,
            "model": self.model,
        }


# ============================================================================
# Entry/Exit Timing Optimization
# ============================================================================

TIMING_OPTIMIZATION_SYSTEM_PROMPT = """You are an entry timing optimizer for an NQ/MNQ futures trading system.

Analyze recent price action and suggest optimal entry timing:
1. Should we enter immediately or wait for a pullback?
2. Would a limit order provide better fill?
3. What's the ideal entry zone based on recent structure?

RULES:
- Be VERY concise (this runs on every signal)
- Base suggestions on observable price structure
- Consider current volatility and spread
- Never delay good trades - bias toward immediate if unclear
- Suggest specific price levels when applicable

Output ONLY valid JSON:
{
  "timing": "immediate|wait_pullback|limit_order",
  "suggested_entry": null,
  "wait_condition": "Wait for retest of X" or null,
  "confidence": 0.7,
  "reason": "Brief explanation"
}"""

TIMING_OPTIMIZATION_USER_TEMPLATE = """Suggest entry timing for this signal:

Signal: {signal_type} {direction} at ${entry_price:.2f}
Stop: ${stop_loss:.2f} ({stop_dist:.1f} pts)
Current Price: ${current_price:.2f}
ATR: {atr:.2f} pts

Recent Price Action (last 5 bars):
{recent_bars}

Key Levels:
- Recent High: ${recent_high:.2f}
- Recent Low: ${recent_low:.2f}
- VWAP: ${vwap:.2f}

Suggest entry timing as JSON:"""


@dataclass
class TimingSuggestion:
    """Entry timing suggestion."""
    timing: str = "immediate"  # immediate, wait_pullback, limit_order
    suggested_entry: Optional[float] = None
    wait_condition: Optional[str] = None
    confidence: float = 0.7
    reason: str = ""
    
    # Metadata
    latency_ms: int = 0
    error: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "timing": self.timing,
            "suggested_entry": self.suggested_entry,
            "wait_condition": self.wait_condition,
            "confidence": self.confidence,
            "reason": self.reason,
            "latency_ms": self.latency_ms,
            "error": self.error,
        }
    
    def format_telegram(self) -> str:
        """Format for Telegram (only if not immediate)."""
        if self.error or self.timing == "immediate":
            return ""
        
        emoji = "⏱️" if self.timing == "wait_pullback" else "📍"
        msg = f"{emoji} *Timing:* {self.timing.replace('_', ' ').title()}"
        
        if self.suggested_entry:
            msg += f" @ ${self.suggested_entry:.2f}"
        
        if self.wait_condition:
            msg += f"\n_{self.wait_condition}_"
        
        return msg
    
    @classmethod
    def immediate(cls) -> "TimingSuggestion":
        """Default immediate entry."""
        return cls(timing="immediate", confidence=1.0)


class EntryTimingOptimizer:
    """
    Suggests optimal entry timing based on price action.
    
    Lightweight analysis that runs on each signal to suggest:
    - Immediate entry vs waiting for pullback
    - Limit order placement
    - Entry zone optimization
    """
    
    def __init__(
        self,
        enabled: bool = True,
        model: str = "claude-sonnet-4-20250514",
        timeout_seconds: float = 3.0,
    ):
        """
        Initialize the timing optimizer.
        
        Args:
            enabled: Whether optimization is enabled
            model: Claude model to use
            timeout_seconds: Timeout (keep short)
        """
        self.enabled = enabled
        self.model = model
        self.timeout_seconds = timeout_seconds
        
        self._client: Optional[ClaudeClient] = None
        if enabled and OPENAI_AVAILABLE:
            try:
                self._client = get_claude_client()
            except Exception as e:
                logger.warning(f"Failed to initialize Claude for timing optimizer: {e}")
        
        self._total_suggestions = 0
        
        status = "enabled" if self._client else "disabled"
        logger.info(f"EntryTimingOptimizer initialized: {status}")
    
    @property
    def is_available(self) -> bool:
        """Check if optimizer is available."""
        return self.enabled and self._client is not None
    
    def suggest_timing(
        self,
        signal: Dict,
        recent_bars: Optional[List[Dict]] = None,
        current_price: Optional[float] = None,
    ) -> TimingSuggestion:
        """
        Suggest entry timing for a signal.
        
        Args:
            signal: Signal dictionary
            recent_bars: Recent OHLCV bars (last 5-10)
            current_price: Current market price
            
        Returns:
            TimingSuggestion
        """
        if not self.is_available:
            return TimingSuggestion.immediate()
        
        start_time = datetime.now(timezone.utc)
        self._total_suggestions += 1
        
        try:
            user_prompt = self._build_prompt(signal, recent_bars, current_price)
            
            response = self._client.chat(
                messages=[{"role": "user", "content": user_prompt}],
                system_prompt=TIMING_OPTIMIZATION_SYSTEM_PROMPT,
                max_tokens=150,
            )
            
            suggestion = self._parse_response(response)
            suggestion.latency_ms = int(
                (datetime.now(timezone.utc) - start_time).total_seconds() * 1000
            )
            
            return suggestion
            
        except Exception as e:
            logger.debug(f"Timing suggestion failed: {e}")
            return TimingSuggestion.immediate()
    
    async def suggest_timing_async(
        self,
        signal: Dict,
        recent_bars: Optional[List[Dict]] = None,
        current_price: Optional[float] = None,
    ) -> TimingSuggestion:
        """Suggest timing asynchronously with timeout."""
        if not self.is_available:
            return TimingSuggestion.immediate()
        
        try:
            loop = asyncio.get_event_loop()
            result = await asyncio.wait_for(
                loop.run_in_executor(
                    None,
                    self.suggest_timing,
                    signal,
                    recent_bars,
                    current_price,
                ),
                timeout=self.timeout_seconds,
            )
            return result
        except asyncio.TimeoutError:
            return TimingSuggestion.immediate()
        except Exception:
            return TimingSuggestion.immediate()
    
    def _build_prompt(
        self,
        signal: Dict,
        recent_bars: Optional[List[Dict]],
        current_price: Optional[float],
    ) -> str:
        """Build prompt for timing analysis."""
        entry_price = signal.get("entry_price", 0)
        stop_loss = signal.get("stop_loss", 0)
        direction = signal.get("direction", "long")
        
        if direction == "long":
            stop_dist = entry_price - stop_loss
        else:
            stop_dist = stop_loss - entry_price
        
        current = current_price or entry_price
        
        # Format recent bars
        bar_lines = []
        if recent_bars:
            for i, bar in enumerate(recent_bars[-5:]):
                o = bar.get("open", 0)
                h = bar.get("high", 0)
                l = bar.get("low", 0)
                c = bar.get("close", 0)
                bar_lines.append(f"  {i+1}. O:{o:.2f} H:{h:.2f} L:{l:.2f} C:{c:.2f}")
        recent_bars_str = "\n".join(bar_lines) if bar_lines else "  (not available)"
        
        # Key levels
        if recent_bars:
            recent_high = max(b.get("high", 0) for b in recent_bars[-10:])
            recent_low = min(b.get("low", float("inf")) for b in recent_bars[-10:])
        else:
            recent_high = entry_price + stop_dist
            recent_low = entry_price - stop_dist
        
        vwap = signal.get("vwap_data", {}).get("vwap", entry_price)
        atr = signal.get("indicators", {}).get("atr", stop_dist)
        
        return TIMING_OPTIMIZATION_USER_TEMPLATE.format(
            signal_type=signal.get("type", "unknown"),
            direction=direction,
            entry_price=entry_price,
            stop_loss=stop_loss,
            stop_dist=stop_dist,
            current_price=current,
            recent_bars=recent_bars_str,
            recent_high=recent_high,
            recent_low=recent_low,
            vwap=vwap,
            atr=atr,
        )
    
    def _parse_response(self, response: str) -> TimingSuggestion:
        """Parse timing response."""
        try:
            response = response.strip()
            if response.startswith("```"):
                lines = response.split("\n")
                response = "\n".join(lines[1:-1] if lines[-1].startswith("```") else lines[1:])
            
            data = json.loads(response)
            
            return TimingSuggestion(
                timing=str(data.get("timing", "immediate")),
                suggested_entry=data.get("suggested_entry"),
                wait_condition=data.get("wait_condition"),
                confidence=float(data.get("confidence", 0.7)),
                reason=str(data.get("reason", "")),
            )
        except json.JSONDecodeError:
            return TimingSuggestion.immediate()


def get_signal_annotator(config: Optional[Dict] = None) -> Optional[LLMSignalAnnotator]:
    """
    Factory function to create a signal annotator from configuration.
    
    Args:
        config: Configuration dictionary with llm_signal_annotation settings
        
    Returns:
        LLMSignalAnnotator instance or None if disabled
    """
    if config is None:
        config = {}
    
    llm_config = config.get("llm_signal_annotation", {})
    
    if not llm_config.get("enabled", False):
        logger.debug("LLM signal annotation disabled in config")
        return None
    
    return LLMSignalAnnotator(
        enabled=True,
        model=llm_config.get("model", "claude-sonnet-4-20250514"),
        timeout_seconds=llm_config.get("timeout_seconds", 5.0),
        batch_mode=llm_config.get("batch_mode", False),
    )


def get_timing_optimizer(config: Optional[Dict] = None) -> Optional[EntryTimingOptimizer]:
    """
    Factory function to create an entry timing optimizer.
    
    Args:
        config: Configuration dictionary
        
    Returns:
        EntryTimingOptimizer instance or None if disabled
    """
    if config is None:
        config = {}
    
    # Timing optimizer piggybacks on signal annotation config
    llm_config = config.get("llm_signal_annotation", {})
    
    if not llm_config.get("enabled", False):
        return None
    
    # Check for explicit timing config or inherit from annotation
    timing_config = config.get("llm_timing_optimization", {})
    
    return EntryTimingOptimizer(
        enabled=timing_config.get("enabled", llm_config.get("enabled", False)),
        model=timing_config.get("model", llm_config.get("model", "claude-sonnet-4-20250514")),
        timeout_seconds=timing_config.get("timeout_seconds", 3.0),
    )

