"""
LangGraph State Management for Multi-Agent Trading System.

Defines the shared state schema that all agents use to communicate and collaborate.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator, model_validator

from pearlalgo.core.portfolio import Portfolio
from pearlalgo.futures.risk import RiskState as FuturesRiskState


class MarketData(BaseModel):
    """Market data for a symbol."""

    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0
    vwap: Optional[float] = None

    # Order book data (if available)
    bid: Optional[float] = None
    ask: Optional[float] = None
    bid_size: Optional[float] = None
    ask_size: Optional[float] = None

    # Crypto-specific (funding rates, OI)
    funding_rate: Optional[float] = None
    open_interest: Optional[float] = None

    # Additional metadata
    metadata: Dict[str, Any] = Field(default_factory=dict)


class Signal(BaseModel):
    """Trading signal generated by Quant Research Agent."""

    symbol: str
    timestamp: datetime
    side: Literal["long", "short", "flat"]
    strategy_name: str
    confidence: float = Field(ge=0.0, le=1.0)  # 0.0 to 1.0

    # Entry/exit levels (aliases for compatibility)
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    
    # Aliases for entry, stop, target (for compatibility with plan requirements)
    @property
    def entry(self) -> Optional[float]:
        """Alias for entry_price."""
        return self.entry_price
    
    @property
    def stop(self) -> Optional[float]:
        """Alias for stop_loss."""
        return self.stop_loss
    
    @property
    def target(self) -> Optional[float]:
        """Alias for take_profit."""
        return self.take_profit
    
    @property
    def rationale(self) -> Optional[str]:
        """Alias for reasoning."""
        return self.reasoning

    # Indicators used
    indicators: Dict[str, Any] = Field(default_factory=dict)

    # Reasoning (from LLM if used)
    reasoning: Optional[str] = None

    # Regime detection
    regime: Optional[Literal["trending", "ranging", "volatile"]] = None

    # Additional metadata
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    @field_validator('entry_price', 'stop_loss', 'take_profit')
    @classmethod
    def validate_prices(cls, v: Optional[float]) -> Optional[float]:
        """Validate prices are positive if provided."""
        if v is not None and v <= 0:
            raise ValueError("Prices must be positive")
        return v


class PositionDecision(BaseModel):
    """Final position decision from Portfolio/Execution Agent."""

    symbol: str
    timestamp: datetime
    action: Literal["enter_long", "enter_short", "exit", "hold", "reduce"]
    size: int  # Contract/shares size (positive for long, negative for short)

    # Prices
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None

    # Risk metrics
    risk_amount: float  # Dollar risk for this trade
    risk_percent: float  # Risk as % of account

    # Reasoning
    reasoning: str

    # Order IDs (after execution)
    order_ids: List[str] = Field(default_factory=list)

    # Status
    status: Literal["pending", "submitted", "filled", "rejected", "cancelled"] = (
        "pending"
    )


class AgentReasoning(BaseModel):
    """Reasoning/logging from each agent."""

    agent_name: str
    timestamp: datetime
    message: str
    level: Literal["debug", "info", "warning", "error"] = "info"
    data: Dict[str, Any] = Field(default_factory=dict)


class TradingState(BaseModel):
    """
    Main state object shared across all agents in the LangGraph workflow.

    This state is passed between agents and updated by each agent as they process.
    """

    # Current timestamp
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # Market data (by symbol)
    market_data: Dict[str, MarketData] = Field(default_factory=dict)

    # Signals (by symbol)
    signals: Dict[str, Signal] = Field(default_factory=dict)

    # Risk state
    risk_state: Optional[FuturesRiskState] = None

    # Portfolio state
    portfolio: Optional[Portfolio] = None

    # Position decisions (by symbol)
    position_decisions: Dict[str, PositionDecision] = Field(default_factory=dict)

    # Agent reasoning/logging
    agent_reasoning: List[AgentReasoning] = Field(default_factory=list)

    # Current workflow step
    current_step: str = "market_data"  # market_data -> quant_research -> risk_manager -> portfolio_execution

    # Error tracking
    errors: List[str] = Field(default_factory=list)

    # Configuration snapshot
    config: Dict[str, Any] = Field(default_factory=dict)

    # Performance metrics
    equity_curve: List[float] = Field(default_factory=list)
    daily_pnl: float = 0.0
    total_pnl: float = 0.0

    # Flags
    trading_enabled: bool = True
    kill_switch_triggered: bool = False

    model_config = {
        "arbitrary_types_allowed": True
    }  # Allow Portfolio and RiskState objects
    
    @model_validator(mode='after')
    def validate_state_transitions(self):
        """Validate state transitions and consistency."""
        # If kill switch is triggered, trading should be disabled
        if self.kill_switch_triggered and self.trading_enabled:
            self.trading_enabled = False
        
        # Validate equity curve is not empty if portfolio exists
        if self.portfolio and not self.equity_curve:
            self.equity_curve = [self.portfolio.cash]
        
        # Validate daily PnL consistency
        if self.portfolio:
            current_equity = self.portfolio.cash + sum(
                pos.realized_pnl + (pos.unrealized_pnl or 0.0)
                for pos in self.portfolio.positions.values()
            )
            if self.equity_curve:
                initial_equity = self.equity_curve[0]
                calculated_daily_pnl = current_equity - initial_equity
                # Allow small floating point differences
                if abs(calculated_daily_pnl - self.daily_pnl) > 0.01:
                    self.daily_pnl = calculated_daily_pnl
        
        return self


def create_initial_state(
    portfolio: Portfolio,
    config: Dict[str, Any],
    timestamp: Optional[datetime] = None,
) -> TradingState:
    """Create initial trading state."""
    if timestamp is None:
        timestamp = datetime.now(timezone.utc)
    return TradingState(
        timestamp=timestamp,
        portfolio=portfolio,
        config=config,
        equity_curve=[portfolio.cash] if portfolio else [],
    )


def add_agent_reasoning(
    state: TradingState,
    agent_name: str,
    message: str,
    level: Literal["debug", "info", "warning", "error"] = "info",
    data: Optional[Dict[str, Any]] = None,
) -> TradingState:
    """Helper to add agent reasoning to state."""
    reasoning = AgentReasoning(
        agent_name=agent_name,
        timestamp=datetime.now(timezone.utc),
        message=message,
        level=level,
        data=data or {},
    )
    state.agent_reasoning.append(reasoning)
    # Keep only last 1000 reasoning entries to prevent memory bloat
    if len(state.agent_reasoning) > 1000:
        state.agent_reasoning = state.agent_reasoning[-1000:]
    return state
