"""
LangGraph State Management for Multi-Agent Trading System

Defines the shared state schema that all agents operate on.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class MarketData(BaseModel):
    """Market data for a symbol."""
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0
    oi: Optional[float] = None  # Open interest (for futures/perps)
    funding_rate: Optional[float] = None  # Funding rate (for crypto perps)
    order_book: Optional[Dict[str, Any]] = None
    source: str = "unknown"  # "ibkr", "polygon", "bybit", etc.


class Signal(BaseModel):
    """Trading signal generated by Quant Research Agent."""
    symbol: str
    side: str  # "long", "short", "flat"
    confidence: float = Field(ge=0.0, le=1.0)
    strategy_name: str
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    indicators: Dict[str, Any] = Field(default_factory=dict)
    reasoning: str = ""  # LLM-generated reasoning
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class RiskState(BaseModel):
    """Risk state computed by Risk Manager Agent."""
    status: str  # "OK", "NEAR_LIMIT", "HARD_STOP", "COOLDOWN", "PAUSED"
    account_equity: float
    daily_pnl: float
    drawdown_pct: float
    max_drawdown_pct: float = 0.15  # Hard limit: 15%
    remaining_loss_buffer: float
    position_size: int = 0
    risk_per_trade_pct: float = 0.02  # Hard limit: 2%
    volatility_target: float = 0.0075  # 0.75% daily vol target
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    reasoning: str = ""
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class Position(BaseModel):
    """Current position in portfolio."""
    symbol: str
    size: int  # Positive for long, negative for short
    entry_price: float
    current_price: float
    unrealized_pnl: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    entry_time: datetime


class TradeDecision(BaseModel):
    """Final trade decision from Portfolio/Execution Agent."""
    symbol: str
    action: str  # "BUY", "SELL", "HOLD", "CLOSE"
    quantity: int
    order_type: str = "MKT"  # "MKT", "LMT", "STP"
    limit_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reasoning: str = ""
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AgentReasoning(BaseModel):
    """Reasoning from an agent."""
    agent_name: str
    reasoning: str
    data: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class TradingState(BaseModel):
    """
    Main state object shared across all agents in the LangGraph workflow.
    
    This state is passed between agents and updated by each agent.
    """
    # Market data (updated by Market Data Agent)
    market_data: Dict[str, MarketData] = Field(default_factory=dict)
    
    # Signals (generated by Quant Research Agent)
    signals: List[Signal] = Field(default_factory=list)
    
    # Risk state (computed by Risk Manager Agent)
    risk_state: Optional[RiskState] = None
    
    # Current positions (tracked by Portfolio/Execution Agent)
    positions: Dict[str, Position] = Field(default_factory=dict)
    
    # Trade decisions (final decisions from Portfolio/Execution Agent)
    trade_decisions: List[TradeDecision] = Field(default_factory=list)
    
    # Agent reasoning (for logging and debugging)
    agent_reasoning: List[AgentReasoning] = Field(default_factory=list)
    
    # Configuration
    symbols: List[str] = Field(default_factory=list)
    broker: str = "ibkr"
    trading_mode: str = "paper"  # "paper" or "live"
    
    # Portfolio state
    account_equity: float = 100000.0
    cash: float = 100000.0
    daily_pnl: float = 0.0
    total_pnl: float = 0.0
    
    # Metadata
    cycle_count: int = 0
    last_update: datetime = Field(default_factory=datetime.utcnow)
    errors: List[str] = Field(default_factory=list)
    
    class Config:
        arbitrary_types_allowed = True


def create_initial_state(
    symbols: List[str],
    broker: str = "ibkr",
    trading_mode: str = "paper",
    initial_cash: float = 100000.0,
) -> TradingState:
    """Create initial trading state."""
    return TradingState(
        symbols=symbols,
        broker=broker,
        trading_mode=trading_mode,
        account_equity=initial_cash,
        cash=initial_cash,
    )

