"""
LangGraph State Management for Multi-Agent Trading System.

Defines the shared state schema that all agents use to communicate and collaborate.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field

from pearlalgo.core.portfolio import Portfolio
from pearlalgo.futures.risk import RiskState as FuturesRiskState


class MarketData(BaseModel):
    """Market data for a symbol."""
    
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0
    vwap: Optional[float] = None
    
    # Order book data (if available)
    bid: Optional[float] = None
    ask: Optional[float] = None
    bid_size: Optional[float] = None
    ask_size: Optional[float] = None
    
    # Crypto-specific (funding rates, OI)
    funding_rate: Optional[float] = None
    open_interest: Optional[float] = None
    
    # Additional metadata
    metadata: Dict[str, Any] = Field(default_factory=dict)


class Signal(BaseModel):
    """Trading signal generated by Quant Research Agent."""
    
    symbol: str
    timestamp: datetime
    side: Literal["long", "short", "flat"]
    strategy_name: str
    confidence: float = Field(ge=0.0, le=1.0)  # 0.0 to 1.0
    
    # Entry/exit levels
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    
    # Indicators used
    indicators: Dict[str, Any] = Field(default_factory=dict)
    
    # Reasoning (from LLM if used)
    reasoning: Optional[str] = None
    
    # Regime detection
    regime: Optional[Literal["trending", "ranging", "volatile"]] = None
    
    # Additional metadata
    metadata: Dict[str, Any] = Field(default_factory=dict)


class PositionDecision(BaseModel):
    """Final position decision from Portfolio/Execution Agent."""
    
    symbol: str
    timestamp: datetime
    action: Literal["enter_long", "enter_short", "exit", "hold", "reduce"]
    size: int  # Contract/shares size (positive for long, negative for short)
    
    # Prices
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    
    # Risk metrics
    risk_amount: float  # Dollar risk for this trade
    risk_percent: float  # Risk as % of account
    
    # Reasoning
    reasoning: str
    
    # Order IDs (after execution)
    order_ids: List[str] = Field(default_factory=list)
    
    # Status
    status: Literal["pending", "submitted", "filled", "rejected", "cancelled"] = "pending"


class AgentReasoning(BaseModel):
    """Reasoning/logging from each agent."""
    
    agent_name: str
    timestamp: datetime
    message: str
    level: Literal["debug", "info", "warning", "error"] = "info"
    data: Dict[str, Any] = Field(default_factory=dict)


class TradingState(BaseModel):
    """
    Main state object shared across all agents in the LangGraph workflow.
    
    This state is passed between agents and updated by each agent as they process.
    """
    
    # Current timestamp
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    
    # Market data (by symbol)
    market_data: Dict[str, MarketData] = Field(default_factory=dict)
    
    # Signals (by symbol)
    signals: Dict[str, Signal] = Field(default_factory=dict)
    
    # Risk state
    risk_state: Optional[FuturesRiskState] = None
    
    # Portfolio state
    portfolio: Optional[Portfolio] = None
    
    # Position decisions (by symbol)
    position_decisions: Dict[str, PositionDecision] = Field(default_factory=dict)
    
    # Agent reasoning/logging
    agent_reasoning: List[AgentReasoning] = Field(default_factory=list)
    
    # Current workflow step
    current_step: str = "market_data"  # market_data -> quant_research -> risk_manager -> portfolio_execution
    
    # Error tracking
    errors: List[str] = Field(default_factory=list)
    
    # Configuration snapshot
    config: Dict[str, Any] = Field(default_factory=dict)
    
    # Performance metrics
    equity_curve: List[float] = Field(default_factory=list)
    daily_pnl: float = 0.0
    total_pnl: float = 0.0
    
    # Flags
    trading_enabled: bool = True
    kill_switch_triggered: bool = False
    
    class Config:
        arbitrary_types_allowed = True  # Allow Portfolio and RiskState objects


def create_initial_state(
    portfolio: Portfolio,
    config: Dict[str, Any],
    timestamp: Optional[datetime] = None,
) -> TradingState:
    """Create initial trading state."""
    return TradingState(
        timestamp=timestamp or datetime.utcnow(),
        portfolio=portfolio,
        config=config,
        equity_curve=[portfolio.cash] if portfolio else [],
    )


def add_agent_reasoning(
    state: TradingState,
    agent_name: str,
    message: str,
    level: Literal["debug", "info", "warning", "error"] = "info",
    data: Optional[Dict[str, Any]] = None,
) -> TradingState:
    """Helper to add agent reasoning to state."""
    reasoning = AgentReasoning(
        agent_name=agent_name,
        timestamp=datetime.utcnow(),
        message=message,
        level=level,
        data=data or {},
    )
    state.agent_reasoning.append(reasoning)
    # Keep only last 1000 reasoning entries to prevent memory bloat
    if len(state.agent_reasoning) > 1000:
        state.agent_reasoning = state.agent_reasoning[-1000:]
    return state
