"""
Indicator Base Class

Abstract base class for all custom indicators. Provides a unified interface
for calculating indicators, generating signals, and extracting features.

Each indicator should:
1. Add columns to the DataFrame via calculate()
2. Optionally generate rule-based signals via generate_signal()
3. Extract numeric features for the learning system via as_features()
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

import pandas as pd


@dataclass
class IndicatorSignal:
    """
    Signal generated by an indicator.
    
    Attributes:
        type: Signal type identifier (e.g., "sd_zone_bounce_long")
        direction: "long" or "short"
        confidence: Confidence score 0-1
        entry_price: Suggested entry price
        stop_loss: Suggested stop loss price
        take_profit: Suggested take profit price
        reason: Human-readable reason for the signal
        metadata: Additional indicator-specific data
    """
    type: str
    direction: str
    confidence: float
    entry_price: float
    stop_loss: float
    take_profit: float
    reason: str
    metadata: Dict[str, Any] = None
    
    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for signal processing."""
        return {
            "type": self.type,
            "direction": self.direction,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "reason": self.reason,
            "indicator_metadata": self.metadata,
        }


class IndicatorBase(ABC):
    """
    Abstract base class for custom indicators.
    
    Subclasses must implement:
    - calculate(): Add indicator columns to DataFrame
    - as_features(): Extract numeric features from latest bar
    - generate_signal(): Optionally generate trading signals
    
    Properties:
    - name: Unique identifier for the indicator
    - description: Human-readable description
    - required_columns: List of required DataFrame columns
    """
    
    def __init__(self, config: Optional[Dict] = None):
        """
        Initialize indicator with optional configuration.
        
        Args:
            config: Indicator-specific configuration dictionary
        """
        self.config = config or {}
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Unique identifier for the indicator."""
        pass
    
    @property
    @abstractmethod
    def description(self) -> str:
        """Human-readable description of the indicator."""
        pass
    
    @property
    def required_columns(self) -> List[str]:
        """List of required DataFrame columns. Default: OHLCV."""
        return ["open", "high", "low", "close", "volume"]
    
    def validate_dataframe(self, df: pd.DataFrame) -> bool:
        """
        Validate that DataFrame has required columns.
        
        Args:
            df: DataFrame to validate
            
        Returns:
            True if valid, False otherwise
        """
        if df is None or df.empty:
            return False
        
        df_cols = [c.lower() for c in df.columns]
        for col in self.required_columns:
            if col.lower() not in df_cols:
                return False
        
        return True
    
    def normalize_columns(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Normalize column names to lowercase.
        
        Args:
            df: DataFrame with potentially mixed-case columns
            
        Returns:
            DataFrame with lowercase column names
        """
        df = df.copy()
        df.columns = [c.lower() for c in df.columns]
        return df
    
    @abstractmethod
    def calculate(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate indicator and add columns to DataFrame.
        
        This method should:
        1. Validate input DataFrame
        2. Calculate indicator values
        3. Add new columns with indicator prefix (e.g., "sd_zone_upper")
        4. Return modified DataFrame
        
        Args:
            df: DataFrame with OHLCV data
            
        Returns:
            DataFrame with added indicator columns
        """
        pass
    
    @abstractmethod
    def as_features(self, latest: pd.Series, df: Optional[pd.DataFrame] = None) -> Dict[str, float]:
        """
        Extract numeric features from the latest bar for the learning system.
        
        Features should be:
        - Normalized to 0-1 range where possible
        - Named with indicator prefix (e.g., "sd_zone_distance_pct")
        - Finite (no NaN/Inf values)
        
        Args:
            latest: Latest bar data (from df.iloc[-1])
            df: Full DataFrame (optional, for lookback calculations)
            
        Returns:
            Dictionary of feature names to float values
        """
        pass
    
    def generate_signal(
        self,
        latest: pd.Series,
        df: pd.DataFrame,
        atr: Optional[float] = None,
    ) -> Optional[IndicatorSignal]:
        """
        Generate a trading signal based on indicator state.
        
        This method is optional - not all indicators generate signals.
        Override this method to implement signal generation logic.
        
        Args:
            latest: Latest bar data
            df: Full DataFrame with indicator columns
            atr: Current ATR value (for stop/target calculation)
            
        Returns:
            IndicatorSignal if conditions are met, None otherwise
        """
        return None
    
    def get_signal_types(self) -> List[str]:
        """
        Get list of signal types this indicator can generate.
        
        Used for registration and configuration.
        
        Returns:
            List of signal type identifiers (e.g., ["sd_zone_bounce_long", "sd_zone_bounce_short"])
        """
        return []
    
    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.name})"

